// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoCGkrRo7nPJuFNVnGRQN0LLaUgKj_j60',
    appId: '1:193829108580:web:95356579b464af4e2d9871',
    messagingSenderId: '193829108580',
    projectId: 'employee-management-dash-8a92f',
    authDomain: 'employee-management-dash-8a92f.firebaseapp.com',
    storageBucket: 'employee-management-dash-8a92f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMONhMFDM-0HttDgBQ9xPRGrapAFJcx34',
    appId: '1:193829108580:android:656fd2d38c6d00f92d9871',
    messagingSenderId: '193829108580',
    projectId: 'employee-management-dash-8a92f',
    storageBucket: 'employee-management-dash-8a92f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL52n2NCR1_eVJj3Vg9x6NtEyBytUTdDU',
    appId: '1:193829108580:ios:383a87c9470a1e712d9871',
    messagingSenderId: '193829108580',
    projectId: 'employee-management-dash-8a92f',
    storageBucket: 'employee-management-dash-8a92f.appspot.com',
    iosBundleId: 'com.example.employeeManagementDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoCGkrRo7nPJuFNVnGRQN0LLaUgKj_j60',
    appId: '1:193829108580:web:4858bced97dccfdf2d9871',
    messagingSenderId: '193829108580',
    projectId: 'employee-management-dash-8a92f',
    authDomain: 'employee-management-dash-8a92f.firebaseapp.com',
    storageBucket: 'employee-management-dash-8a92f.appspot.com',
  );
}
